import { ActivityLevel, CalorieGoal, UserRole, AccountStatus } from './types'; // UserRole and AccountStatus are used here

export const APP_NAME = "منصة التدريب الرياضي";

// MOCKED_PLANS has been removed. Plans will be fetched from the database.
// export const MOCKED_PLANS: TrainingPlan[] = [
//   { id: 'plan1', name: 'خطة المبتدئين', description: 'خطة شاملة للمبتدئين لبناء الأساس.', price: 50, durationMonths: 1 },
//   { id: 'plan2', name: 'خطة متوسطة', description: 'للمستوى المتوسط لزيادة القوة والتحمل.', price: 75, durationMonths: 2 },
//   { id: 'plan3', name: 'خطة متقدمة', description: 'للمتقدمين لتحقيق أقصى أداء.', price: 100, durationMonths: 3 },
// ];

export const ARABIC_STRINGS = {
  login: "تسجيل الدخول",
  signup: "إنشاء حساب",
  dashboard: "لوحة التحكم",
  adminDashboard: "لوحة تحكم المدير",
  trainerDashboard: "لوحة تحكم المدرب",
  traineeDashboard: "لوحة تحكم المتدرب",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  name: "الاسم الكامل",
  phoneNumber: "رقم الهاتف",
  country: "الدولة",
  selectPlan: "اختر خطة تدريبية",
  users: "المستخدمون",
  trainers: "المدربون",
  trainees: "المتدربون",
  plans: "الخطط التدريبية",
  notifications: "الإشعارات",
  settings: "الإعدادات",
  logout: "تسجيل الخروج",
  calorieCalculator: "حاسبة السعرات الحرارية",
  age: "العمر (سنوات)",
  weight: "الوزن (كجم)",
  height: "الطول (سم)",
  activityLevel: "مستوى النشاط",
  goal: "الهدف",
  gender: "الجنس",
  male: "ذكر",
  female: "أنثى",
  calculate: "احسب",
  dailyCalories: "السعرات الحرارية اليومية المقدرة:",
  
  activityLevels: {
    [ActivityLevel.SEDENTARY]: "خامل (تمارين قليلة أو معدومة)",
    [ActivityLevel.LIGHT]: "خفيف (تمارين خفيفة 1-3 أيام/أسبوع)",
    [ActivityLevel.MODERATE]: "متوسط (تمارين متوسطة 3-5 أيام/أسبوع)",
    [ActivityLevel.ACTIVE]: "نشيط (تمارين قاسية 6-7 أيام/أسبوع)",
    [ActivityLevel.VERY_ACTIVE]: "نشيط جداً (تمارين قاسية جداً وعمل بدني)",
  },
  calorieGoals: {
    [CalorieGoal.LOSE_WEIGHT]: "إنقاص الوزن",
    [CalorieGoal.MAINTAIN_WEIGHT]: "الحفاظ على الوزن",
    [CalorieGoal.GAIN_WEIGHT]: "زيادة الوزن",
  },
  approve: "موافقة",
  reject: "رفض",
  pendingAccounts: "الحسابات المعلقة",
  activeAccounts: "الحسابات النشطة",
  assignAsTrainer: "تعيين كمدرب",
  manageUsers: "إدارة المستخدمين",
  addPlan: "إضافة خطة",
  editPlan: "تعديل خطة",
  deletePlan: "حذف خطة",
  planName: "اسم الخطة",
  planDescription: "وصف الخطة",
  planPrice: "سعر الخطة (بالعملة المحلية)",
  planDuration: "مدة الخطة (أشهر)",
  save: "حفظ",
  cancel: "إلغاء",
  sendNotification: "إرسال إشعار",
  recipient: "المستلم",
  title: "العنوان",
  message: "الرسالة",
  send: "إرسال",
  allUsers: "جميع المستخدمين",
  allTrainers: "جميع المدربين",
  allTrainees: "جميع المتدربين",
  myTrainees: "المتدربون الخاصون بي",
  addTrainingVideo: "إضافة فيديو تدريبي",
  videoTitle: "عنوان الفيديو",
  youtubeLink: "رابط يوتيوب",
  uploadNutritionFile: "رفع ملف تغذية",
  fileName: "اسم الملف",
  viewProfile: "عرض الملف الشخصي",
  trainingVideos: "فيديوهات التدريب",
  nutritionFiles: "ملفات التغذية",
  mySchedule: "جدولي التدريبي",
  chatWithTrainer: "محادثة مع المدرب",
  ratePlan: "تقييم الخطة",
  rateTrainer: "تقييم المدرب",
  submitRating: "إرسال التقييم",
  comments: "تعليقات (اختياري)",
  stars: "نجوم",
  noDataAvailable: "لا توجد بيانات متاحة.",
  confirmAction: "تأكيد الإجراء",
  areYouSure: "هل أنت متأكد أنك تريد المتابعة؟",
  yes: "نعم",
  no: "لا",
  status: "الحالة",
  actions: "إجراءات",
  viewDetails: "عرض التفاصيل",
  edit: "تعديل",
  delete: "حذف",
  userManagement: "إدارة المستخدمين",
  planManagement: "إدارة الخطط",
  statistics: "الإحصائيات",
  filterByStatus: "فلترة حسب الحالة",
  // The following direct string keys were causing conflicts and have been removed.
  // The enum-based keys below will provide these translations.
  // active: "نشط",
  // pending: "معلق",
  // rejected: "مرفوض",
  // trainer: "مدرب",
  // trainee: "متدرب",
  selectUser: "اختر مستخدم",
  selectTrainer: "اختر مدرب",
  linkTraineeToTrainer: "ربط متدرب بمدرب",
  [UserRole.ADMIN]: "مدير",
  [UserRole.TRAINER]: "مدرب",
  [UserRole.TRAINEE]: "متدرب",
  [AccountStatus.ACTIVE]: "نشط",
  [AccountStatus.PENDING]: "معلق",
  [AccountStatus.REJECTED]: "مرفوض",
};

export const DEFAULT_COUNTRY_OPTIONS = [
  { value: "SA", label: "المملكة العربية السعودية" },
  { value: "EG", label: "مصر" },
  { value: "AE", label: "الإمارات العربية المتحدة" },
  { value: "KW", label: "الكويت" },
  { value: "QA", label: "قطر" },
  { value: "JO", label: "الأردن" },
];

// Placeholder API Key for Gemini. In a real app, this MUST come from process.env.API_KEY
// For the purpose of this generated code, we assume process.env.API_KEY is set in the environment.
// const GEMINI_API_KEY = process.env.API_KEY; 
// if (!GEMINI_API_KEY) {
//  console.warn("API_KEY environment variable is not set. Gemini API calls will fail.");
// }
// No explicit declaration of process.env here. It's assumed to be available.